Trying stuff.

diff --git a/initramfs-init-dropbear b/initramfs-init-dropbear
--- a/initramfs-init-dropbear
+++ b/initramfs-init-dropbear
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 # this is the init script version
-VERSION=3.1.0-r3
+VERSION=3.3.0-r1
 SINGLEMODE=no
 sysroot=/sysroot
 splashfile=/.splash.ctrl
@@ -142,11 +142,14 @@ setup_inittab_console(){
 }
 
 # determine the default interface to use if ip=dhcp is set
-# uses the first "eth" interface.
+# uses the first "eth" interface with operstate 'up'.
 ip_choose_if() {
 	for x in /sys/class/net/eth*; do
-		[ -e "$x" ] && echo ${x##*/} && return
+		if grep -iq up $x/operstate;then
+			[ -e "$x" ] && echo ${x##*/} && return
+		fi
 	done
+	[ -e "$x" ] && echo ${x##*/} && return
 }
 
 # ip_set <device> <ip> <netmask> <gateway-ip>
@@ -183,6 +186,8 @@ configure_ip() {
 	local netmask="$4"
 	local device="$6"
 	local autoconf="$7"
+	local dns1="$8"
+	local dns2="$9"
 	case "$client_ip" in
 		off|none|'') return;;
 		dhcp) autoconf="dhcp";;
@@ -209,6 +214,8 @@ configure_ip() {
 		ebegin "Setting IP ($device)..."
 		ip_set "$device" "$client_ip" "$netmask" "$gw_ip"
 		eend $?
+		[ -n "$dns1" ] && echo "nameserver $dns1" >> /etc/resolv.conf
+		[ -n "$dns2" ] && echo "nameserver $dns2" >> /etc/resolv.conf
 	fi
 	MAC_ADDRESS=$(cat /sys/class/net/$device/address)
 }
@@ -221,6 +228,10 @@ relocate_mount() {
 		return
 	fi
 	while read dir; do
+		# skip http(s)/ftp repos for netboot
+		if ! [ -d "$dir" ]; then
+			continue
+		fi
 		local dev=$(df -P "$dir" | tail -1 | awk '{print $1}')
 		local mnt=$(find_mnt $dev $fstab)
 		if [ -n "$mnt" ]; then
@@ -243,6 +254,21 @@ find_boot_repositories() {
 	fi
 }
 
+setup_dropbear() {
+    echo "${1}" > /etc/dropbear/cryptopts
+	# set the unlock_disk script as shell for root
+	sed -i 's|\(root:x:0:0:root:/root:\).*$|\1/etc/dropbear/unlock_disk|' /etc/passwd
+	echo '/etc/dropbear/unlock_disk' > /etc/shells
+
+	# transfer authorized_keys
+	mkdir -p /root/.ssh
+	mv /etc/dropbear/authorized_keys /root/.ssh
+
+	dropbear -R -E -s -j -k
+
+	#[ -b /dev/mapper/${KOPT_cryptdm} ] || return 1
+}
+
 setup_nbd() {
 	modprobe -q nbd max_part=8 || return 1
 	local IFS=, n=0
@@ -258,31 +284,14 @@ setup_nbd() {
 	[ "$n" != 0 ] || return 1
 }
 
-setup_dropbear() {
-	local port="${KOPT_dropbear}"
-	local keys=""
-
-	# set the unlock_disc script as shell for root
-	sed -i 's|\(root:x:0:0:root:/root:\).*$|\1/etc/dropbear/unlock_disk|' /etc/passwd
-	echo '/etc/dropbear/unlock_disk' > /etc/shells
-
-	# transfair authorized_keys
-	mkdir /root/.ssh
-	mv /etc/dropbear/authorized_keys /root/.ssh
-
-	dropbear -R -F -E -s -j -k -p $port
-
-	[ -b /dev/mapper/${KOPT_cryptdm} ] || return 1
-}
-
 # read the kernel options. we need surve things like:
 #  acpi_osi="!Windows 2006" xen-pciback.hide=(01:00.0)
 set -- $(cat /proc/cmdline)
 
 myopts="alpine_dev autodetect autoraid chart cryptroot cryptdm cryptheader cryptoffset
-	debug_init dma dropbear init_args keep_apk_new modules ovl_dev pkgs quiet root_size root
-	usbdelay ip alpine_repo apkovl alpine_start splash blacklist
-	overlaytmpfs rootfstype rootflags nbd resume"
+	cryptdiscards cryptkey dropbear debug_init dma init_args keep_apk_new modules ovl_dev
+	pkgs quiet root_size root usbdelay ip alpine_repo apkovl alpine_start splash
+	blacklist overlaytmpfs rootfstype rootflags nbd resume s390x_net dasd ssh_key"
 
 for opt; do
 	case "$opt" in
@@ -342,7 +351,7 @@ ALPINE_REPO=${KOPT_alpine_repo}
 [ "$KOPT_quiet" = yes ] && dmesg -n 1
 
 # optional blacklist
-for i in ${KOPT_blacklist/,/ }; do
+for i in ${KOPT_blacklist//,/ }; do
 	echo "blacklist $i" >> /etc/modprobe.d/boot-opt-blacklist.conf
 done
 
@@ -358,6 +367,25 @@ mount -t devpts -o gid=5,mode=0620,noexec,nosuid devpts /dev/pts
 [ -d /dev/shm ] || mkdir /dev/shm
 mount -t tmpfs -o nodev,nosuid,noexec shm /dev/shm
 
+if [ -n "$KOPT_dasd" ]; then
+	for mod in dasd_mod dasd_eckd_mod dasd_fba_mod; do
+		modprobe $mod
+	done
+	for _dasd in $(echo "$KOPT_dasd" | tr ',' ' ' ); do
+		echo 1 > /sys/bus/ccw/devices/"${_dasd%%:*}"/online
+	done
+fi
+
+if [ "${KOPT_s390x_net%%,*}" = "qeth_l2" ]; then
+	for mod in qeth qeth_l2 qeth_l3; do
+		modprobe $mod
+	done
+	_channel="${KOPT_s390x_net#*,}"
+	echo "$_channel" > /sys/bus/ccwgroup/drivers/qeth/group
+	echo 1 > /sys/bus/ccwgroup/drivers/qeth/"${_channel%%,*}"/layer2
+	echo 1 > /sys/bus/ccwgroup/drivers/qeth/"${_channel%%,*}"/online
+fi
+
 # load available drivers to get access to modloop media
 ebegin "Loading boot drivers"
 
@@ -370,13 +398,11 @@ if [ -f /etc/modules ] ; then
 fi
 eend 0
 
-if [ -n "$KOPT_dropbear" ]; then
-	configure_ip
-	if [ -n "$KOPT_cryptroot" ]; then
-		setup_dropbear || echo "Failed to uncrypt root via ssh"
-	fi
-elif [ -n "$KOPT_cryptroot" ]; then
+if [ -n "$KOPT_cryptroot" ]; then
 	cryptopts="-c ${KOPT_cryptroot}"
+	if [ "$KOPT_cryptdiscards" = "yes" ]; then
+		cryptopts="$cryptopts -D"
+	fi
 	if [ -n "$KOPT_cryptdm" ]; then
 		cryptopts="$cryptopts -m ${KOPT_cryptdm}"
 	fi
@@ -386,6 +412,15 @@ elif [ -n "$KOPT_cryptroot" ]; then
 	if [ -n "$KOPT_cryptoffset" ]; then
 		cryptopts="$cryptopts -o ${KOPT_cryptoffset}"
 	fi
+	if [ "$KOPT_cryptkey" = "yes" ]; then
+		cryptopts="$cryptopts -k /crypto_keyfile.bin"
+	elif [ -n "$KOPT_cryptkey" ]; then
+		cryptopts="$cryptopts -k ${KOPT_cryptkey}"
+	fi
+fi
+
+if [ "$KOPT_dropbear" = "yes" ]; then
+    setup_dropbear "$cryptopts"
 fi
 
 if [ -n "$KOPT_nbd" ]; then
@@ -408,7 +443,8 @@ if [ -n "$KOPT_root" ]; then
 		$KOPT_root
 
 	if echo "$KOPT_modules $KOPT_rootfstype" | grep -qw btrfs; then
-		/sbin/btrfs device scan || echo "Failed to scan devices for btrfs filesystem."
+		/sbin/btrfs device scan >/dev/null || \
+			echo "Failed to scan devices for btrfs filesystem."
 	fi
 
 	if [ -n "$KOPT_resume" ]; then
@@ -535,6 +571,8 @@ if [ -f "$sysroot/etc/.default_boot_services" -o ! -f "$ovl" ]; then
 	rc_add killprocs shutdown
 	rc_add savecache shutdown
 
+	rc_add firstboot default
+
 	rm -f "$sysroot/etc/.default_boot_services"
 fi
 
@@ -617,7 +655,13 @@ if [ "$KOPT_chart" = yes ]; then
 	pkgs="$pkgs acct"
 fi
 
-apkflags="--initdb --progress --force"
+# add openssh
+if [ -n "$KOPT_ssh_key" ]; then
+	pkgs="$pkgs openssh"
+	rc_add sshd default
+fi
+
+apkflags="--initramfs-diskless-boot --progress"
 if [ -z "$ALPINE_REPO" ]; then
 	apkflags="$apkflags --no-network"
 else
